### ISSUE TITLE
Sequence of layers in sidebar

### ISSUE THREAD

**Issue by Wimklo** [nbelyh/svgpublish-templates#23]
Is it possible to change the sequence/order of layers in the sidebar?
The order in the HTML-file after export is now determined by visio drawing. 
If I'm correct: Visio sorts layers in order of old to new.  
Would be great if order could be easily adjusted, rather then delete all layers and add them in the right order (pretty much work for different files & tabs).

**Comment by nbelyh** [comment]
@Wimklo 
Now the extension takes the order from Visio (1:1). What could be the motivation to change the order? I've just made the layers work 1:1 with Visio, because there were complains that they are not in sync 😅 

Wouldn't it make more sense to re-order them in Visio first (maybe with a macro?).

What is the idea behind - to find the layers faster, in case when there are many? In this case, would a "search box" like the one there is for pages a "good enough" solution?

**Comment by nbelyh** [comment]
I would suggest sorting the layers alphabetically maybe (as an option)? 
So that they are displayed the same way as "Layers" window. In the "Assign to layer" the layout matches the current one.. Just the order of adding. But it would be great to have that feature in Visio someday maybe.

**Comment by nbelyh** [comment]
Added lookup for layers to simplify finding one that is needed:
https://github.com/nbelyh/svgpublish/pull/19

**Comment by nbelyh** [comment]
![image](https://user-images.githubusercontent.com/528366/82949314-abdb8f00-9fa3-11ea-9c7b-22d8f6f50452.png)
I think this is good enough for now; I'd stick to Visio sorting. Finding a layer should not be an issue anymore.

**Comment by nbelyh** [comment]
Still adding sorting as an option

**Comment by nbelyh** [comment]
done
![image](https://user-images.githubusercontent.com/528366/83070546-f0326200-a06b-11ea-9cbd-101d867cb8e6.png)
