### ISSUE TITLE
ContainerStyleDefaults text in tooltip for Shape

### ISSUE THREAD

**Issue by TJF0700** [nbelyh/svgpublish-templates#33]
When I enable the tooltip for shape, I like the tip in the upper right-hand corner, but it always has "ContainerStyleDefaults:" in front of the text displayed.

![Capture](https://user-images.githubusercontent.com/12072851/82579574-a0c3d180-9b53-11ea-8760-09a84c9b31d7.PNG)

**Comment by nbelyh** [comment]
@TJF0700 Looks like it's because of a "non-stock" container maybe. 😄 
If you could share a sample diagram, I'll be able to took into this. Or just post a screenshot of the whole container. for the default ones ,this "ContainerStyleDefaults" does not seem to be coming.
You are on version 1.2.12, right?

**Comment by nbelyh** [comment]
Basically this was thought of for the "cross-functional-flowchart" template, i.e. if you have a large table. May not be properly tested with other containers.

**Comment by nbelyh** [comment]
Now always use label "container" for types which are non-phase and not lane.
https://github.com/nbelyh/svgpublish/commit/3abbb5ce5faa99cf6519511a35c9d9df0d89dda1

**Comment by nbelyh** [comment]
Should be closed in in 1.3
